var annotated_dup =
[
    [ "LLMUnity", "namespaceLLMUnity.html", [
      [ "AlpacaTemplate", "classLLMUnity_1_1AlpacaTemplate.html", null ],
      [ "ChatAttribute", "classLLMUnity_1_1ChatAttribute.html", null ],
      [ "ChatMessage", "structLLMUnity_1_1ChatMessage.html", null ],
      [ "ChatMLTemplate", "classLLMUnity_1_1ChatMLTemplate.html", null ],
      [ "ChatOpenAIRequest", "structLLMUnity_1_1ChatOpenAIRequest.html", null ],
      [ "ChatOpenAIResult", "structLLMUnity_1_1ChatOpenAIResult.html", null ],
      [ "ChatOpenAIResultChoice", "structLLMUnity_1_1ChatOpenAIResultChoice.html", null ],
      [ "ChatOpenAIResultNumTokens", "structLLMUnity_1_1ChatOpenAIResultNumTokens.html", null ],
      [ "ChatRequest", "structLLMUnity_1_1ChatRequest.html", null ],
      [ "ChatResult", "structLLMUnity_1_1ChatResult.html", null ],
      [ "ChatTemplate", "classLLMUnity_1_1ChatTemplate.html", null ],
      [ "ClientAdvancedAttribute", "classLLMUnity_1_1ClientAdvancedAttribute.html", null ],
      [ "ClientAttribute", "classLLMUnity_1_1ClientAttribute.html", null ],
      [ "FloatAttribute", "classLLMUnity_1_1FloatAttribute.html", null ],
      [ "GGUFReader", "classLLMUnity_1_1GGUFReader.html", null ],
      [ "IntAttribute", "classLLMUnity_1_1IntAttribute.html", null ],
      [ "LLama2ChatTemplate", "classLLMUnity_1_1LLama2ChatTemplate.html", null ],
      [ "LLama2Template", "classLLMUnity_1_1LLama2Template.html", null ],
      [ "LLM", "classLLMUnity_1_1LLM.html", null ],
      [ "LLMClient", "classLLMUnity_1_1LLMClient.html", null ],
      [ "LLMUnitySetup", "classLLMUnity_1_1LLMUnitySetup.html", "classLLMUnity_1_1LLMUnitySetup" ],
      [ "MistralChatTemplate", "classLLMUnity_1_1MistralChatTemplate.html", null ],
      [ "MistralInstructTemplate", "classLLMUnity_1_1MistralInstructTemplate.html", null ],
      [ "ModelAddonAdvancedAttribute", "classLLMUnity_1_1ModelAddonAdvancedAttribute.html", null ],
      [ "ModelAddonAttribute", "classLLMUnity_1_1ModelAddonAttribute.html", null ],
      [ "ModelAdvancedAttribute", "classLLMUnity_1_1ModelAdvancedAttribute.html", null ],
      [ "ModelAttribute", "classLLMUnity_1_1ModelAttribute.html", null ],
      [ "ModelExpertAttribute", "classLLMUnity_1_1ModelExpertAttribute.html", null ],
      [ "MultiChatResult", "structLLMUnity_1_1MultiChatResult.html", null ],
      [ "Phi2Template", "classLLMUnity_1_1Phi2Template.html", null ],
      [ "ReaderField", "classLLMUnity_1_1ReaderField.html", null ],
      [ "ReaderTensor", "classLLMUnity_1_1ReaderTensor.html", null ],
      [ "ServerAdvancedAttribute", "classLLMUnity_1_1ServerAdvancedAttribute.html", null ],
      [ "ServerAttribute", "classLLMUnity_1_1ServerAttribute.html", null ],
      [ "ServerStatus", "structLLMUnity_1_1ServerStatus.html", null ],
      [ "TokenizeRequest", "structLLMUnity_1_1TokenizeRequest.html", null ],
      [ "TokenizeResult", "structLLMUnity_1_1TokenizeResult.html", null ],
      [ "ZephyrTemplate", "classLLMUnity_1_1ZephyrTemplate.html", null ]
    ] ]
];