name: Changelog
on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.base_ref, 'release/') && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
            persist-credentials: false
            token: ${{ github.token }}

      - name: Update tooltips
        id: update_tooltips
        run: |
            python .github/update_tooltips.py
            git config --global user.name $GITHUB_ACTOR
            git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
            git add Runtime
            git commit -m "update tooltips"
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ github.token }}
            branch: ${{ github.base_ref }}
